### ISSUE TITLE
header: unexpected EOF

### ISSUE THREAD

**Issue by derit26** [muesli/prism#8] opened 2021-05-03 09:59 UTC
i tested to publish to facebook live but i got a response 

```
Starting RTMP server... 
Waiting for incoming connection...
New connection!
can't write header: unexpected EOF
can't write header: unexpected EOF
```

**Comment by nikolay** [comment] 2021-05-09 03:58
@muesli Is the project abandonware? The issue here is a dupe of https://github.com/muesli/prism/issues/3.

**Comment by muesli** [comment] 2021-05-09 04:07
Certainly not, but I have a whole collection of projects I maintain, so sometimes things are a bit slower. Thanks for the heads up!

**Closed as completed by muesli** 2021-05-09 04:07 UTC
Labels: duplicate
